version: '3.8'

services:
  task-management:
    container_name: task-management
    build:
      context: . #current directory
      dockerfile: ./Dockerfile
      target: development # declared in docker file
    command: npm run start:dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app # changes to
