version: '3.8'

services:
  task-manager:
    container_name: task-manager
    build:
      context: . #current directory
      dockerfile: ./apps/task-manager/Dockerfile
      target: development # declared in docker file
    command: npm run start:dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app # changes to
