version: '3.8'

services:
  task-manager:
    container_name: task-manager
    build:
      context: . # current directory
      dockerfile: ./apps/task-manager/Dockerfile
      target: development # declared in Dockerfile
    command: npm run start:dev
    ports:
      - '3500:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: mongodb-task-manager
    image: mongo:latest
    ports:
      - '27017:27017'
    env_file:
      - db.env
    volumes:
      - mongodb_data:/data/db
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --host mongodb-task-manager --quiet --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 'Health Check Successful' || echo 'Health Check Failed'"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
volumes:
  mongodb_data:
